// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room_downsync_frame.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Direction struct {
	Dx                   float64  `protobuf:"fixed64,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy                   float64  `protobuf:"fixed64,2,opt,name=dy,proto3" json:"dy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Direction) Reset()         { *m = Direction{} }
func (m *Direction) String() string { return proto.CompactTextString(m) }
func (*Direction) ProtoMessage()    {}
func (*Direction) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{0}
}

func (m *Direction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Direction.Unmarshal(m, b)
}
func (m *Direction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Direction.Marshal(b, m, deterministic)
}
func (m *Direction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Direction.Merge(m, src)
}
func (m *Direction) XXX_Size() int {
	return xxx_messageInfo_Direction.Size(m)
}
func (m *Direction) XXX_DiscardUnknown() {
	xxx_messageInfo_Direction.DiscardUnknown(m)
}

var xxx_messageInfo_Direction proto.InternalMessageInfo

func (m *Direction) GetDx() float64 {
	if m != nil {
		return m.Dx
	}
	return 0
}

func (m *Direction) GetDy() float64 {
	if m != nil {
		return m.Dy
	}
	return 0
}

type Treasure struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	X                    float64  `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,6,opt,name=removed,proto3" json:"removed,omitempty"`
	Type                 int32    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Treasure) Reset()         { *m = Treasure{} }
func (m *Treasure) String() string { return proto.CompactTextString(m) }
func (*Treasure) ProtoMessage()    {}
func (*Treasure) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{2}
}

func (m *Treasure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Treasure.Unmarshal(m, b)
}
func (m *Treasure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Treasure.Marshal(b, m, deterministic)
}
func (m *Treasure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Treasure.Merge(m, src)
}
func (m *Treasure) XXX_Size() int {
	return xxx_messageInfo_Treasure.Size(m)
}
func (m *Treasure) XXX_DiscardUnknown() {
	xxx_messageInfo_Treasure.DiscardUnknown(m)
}

var xxx_messageInfo_Treasure proto.InternalMessageInfo

func (m *Treasure) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Treasure) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Treasure) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Treasure) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Treasure) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Treasure) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Treasure) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Bullet struct {
	LocalIdInBattle      int32    `protobuf:"varint,1,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	LinearSpeed          float64  `protobuf:"fixed64,2,opt,name=linearSpeed,proto3" json:"linearSpeed,omitempty"`
	X                    float64  `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bullet) Reset()         { *m = Bullet{} }
func (m *Bullet) String() string { return proto.CompactTextString(m) }
func (*Bullet) ProtoMessage()    {}
func (*Bullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{3}
}

func (m *Bullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bullet.Unmarshal(m, b)
}
func (m *Bullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bullet.Marshal(b, m, deterministic)
}
func (m *Bullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bullet.Merge(m, src)
}
func (m *Bullet) XXX_Size() int {
	return xxx_messageInfo_Bullet.Size(m)
}
func (m *Bullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bullet.DiscardUnknown(m)
}

var xxx_messageInfo_Bullet proto.InternalMessageInfo

func (m *Bullet) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Bullet) GetLinearSpeed() float64 {
	if m != nil {
		return m.LinearSpeed
	}
	return 0
}

func (m *Bullet) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Bullet) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Bullet) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type Trap struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	X                    float64  `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,6,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trap) Reset()         { *m = Trap{} }
func (m *Trap) String() string { return proto.CompactTextString(m) }
func (*Trap) ProtoMessage()    {}
func (*Trap) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{4}
}

func (m *Trap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trap.Unmarshal(m, b)
}
func (m *Trap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trap.Marshal(b, m, deterministic)
}
func (m *Trap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trap.Merge(m, src)
}
func (m *Trap) XXX_Size() int {
	return xxx_messageInfo_Trap.Size(m)
}
func (m *Trap) XXX_DiscardUnknown() {
	xxx_messageInfo_Trap.DiscardUnknown(m)
}

var xxx_messageInfo_Trap proto.InternalMessageInfo

func (m *Trap) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Trap) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Trap) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Trap) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Trap) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Trap) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type SpeedShoes struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocalIdInBattle      int32    `protobuf:"varint,2,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	X                    float64  `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpeedShoes) Reset()         { *m = SpeedShoes{} }
func (m *SpeedShoes) String() string { return proto.CompactTextString(m) }
func (*SpeedShoes) ProtoMessage()    {}
func (*SpeedShoes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{5}
}

func (m *SpeedShoes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeedShoes.Unmarshal(m, b)
}
func (m *SpeedShoes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeedShoes.Marshal(b, m, deterministic)
}
func (m *SpeedShoes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeedShoes.Merge(m, src)
}
func (m *SpeedShoes) XXX_Size() int {
	return xxx_messageInfo_SpeedShoes.Size(m)
}
func (m *SpeedShoes) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeedShoes.DiscardUnknown(m)
}

var xxx_messageInfo_SpeedShoes proto.InternalMessageInfo

func (m *SpeedShoes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SpeedShoes) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *SpeedShoes) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SpeedShoes) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *SpeedShoes) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *SpeedShoes) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Pumpkin struct {
	LocalIdInBattle      int32    `protobuf:"varint,1,opt,name=localIdInBattle,proto3" json:"localIdInBattle,omitempty"`
	LinearSpeed          float64  `protobuf:"fixed64,2,opt,name=linearSpeed,proto3" json:"linearSpeed,omitempty"`
	X                    float64  `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pumpkin) Reset()         { *m = Pumpkin{} }
func (m *Pumpkin) String() string { return proto.CompactTextString(m) }
func (*Pumpkin) ProtoMessage()    {}
func (*Pumpkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{6}
}

func (m *Pumpkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pumpkin.Unmarshal(m, b)
}
func (m *Pumpkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pumpkin.Marshal(b, m, deterministic)
}
func (m *Pumpkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pumpkin.Merge(m, src)
}
func (m *Pumpkin) XXX_Size() int {
	return xxx_messageInfo_Pumpkin.Size(m)
}
func (m *Pumpkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pumpkin.DiscardUnknown(m)
}

var xxx_messageInfo_Pumpkin proto.InternalMessageInfo

func (m *Pumpkin) GetLocalIdInBattle() int32 {
	if m != nil {
		return m.LocalIdInBattle
	}
	return 0
}

func (m *Pumpkin) GetLinearSpeed() float64 {
	if m != nil {
		return m.LinearSpeed
	}
	return 0
}

func (m *Pumpkin) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Pumpkin) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Pumpkin) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type RoomDownsyncFrame struct {
	Id                   int32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RefFrameId           int32                 `protobuf:"varint,2,opt,name=refFrameId,proto3" json:"refFrameId,omitempty"`
	Players              map[int32]*Player     `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SentAt               int64                 `protobuf:"varint,4,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	CountdownNanos       int64                 `protobuf:"varint,5,opt,name=countdownNanos,proto3" json:"countdownNanos,omitempty"`
	Treasures            map[int32]*Treasure   `protobuf:"bytes,6,rep,name=treasures,proto3" json:"treasures,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Traps                map[int32]*Trap       `protobuf:"bytes,7,rep,name=traps,proto3" json:"traps,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Bullets              map[int32]*Bullet     `protobuf:"bytes,8,rep,name=bullets,proto3" json:"bullets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SpeedShoes           map[int32]*SpeedShoes `protobuf:"bytes,9,rep,name=speedShoes,proto3" json:"speedShoes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Pumpkin              map[int32]*Pumpkin    `protobuf:"bytes,10,rep,name=pumpkin,proto3" json:"pumpkin,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoomDownsyncFrame) Reset()         { *m = RoomDownsyncFrame{} }
func (m *RoomDownsyncFrame) String() string { return proto.CompactTextString(m) }
func (*RoomDownsyncFrame) ProtoMessage()    {}
func (*RoomDownsyncFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbf2753c483f827, []int{7}
}

func (m *RoomDownsyncFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDownsyncFrame.Unmarshal(m, b)
}
func (m *RoomDownsyncFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDownsyncFrame.Marshal(b, m, deterministic)
}
func (m *RoomDownsyncFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDownsyncFrame.Merge(m, src)
}
func (m *RoomDownsyncFrame) XXX_Size() int {
	return xxx_messageInfo_RoomDownsyncFrame.Size(m)
}
func (m *RoomDownsyncFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDownsyncFrame.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDownsyncFrame proto.InternalMessageInfo

func (m *RoomDownsyncFrame) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomDownsyncFrame) GetRefFrameId() int32 {
	if m != nil {
		return m.RefFrameId
	}
	return 0
}

func (m *RoomDownsyncFrame) GetPlayers() map[int32]*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomDownsyncFrame) GetSentAt() int64 {
	if m != nil {
		return m.SentAt
	}
	return 0
}

func (m *RoomDownsyncFrame) GetCountdownNanos() int64 {
	if m != nil {
		return m.CountdownNanos
	}
	return 0
}

func (m *RoomDownsyncFrame) GetTreasures() map[int32]*Treasure {
	if m != nil {
		return m.Treasures
	}
	return nil
}

func (m *RoomDownsyncFrame) GetTraps() map[int32]*Trap {
	if m != nil {
		return m.Traps
	}
	return nil
}

func (m *RoomDownsyncFrame) GetBullets() map[int32]*Bullet {
	if m != nil {
		return m.Bullets
	}
	return nil
}

func (m *RoomDownsyncFrame) GetSpeedShoes() map[int32]*SpeedShoes {
	if m != nil {
		return m.SpeedShoes
	}
	return nil
}

func (m *RoomDownsyncFrame) GetPumpkin() map[int32]*Pumpkin {
	if m != nil {
		return m.Pumpkin
	}
	return nil
}

func init() {
	proto.RegisterType((*Direction)(nil), "models.Direction")
	proto.RegisterType((*Player)(nil), "models.Player")
	proto.RegisterType((*Treasure)(nil), "models.Treasure")
	proto.RegisterType((*Bullet)(nil), "models.Bullet")
	proto.RegisterType((*Trap)(nil), "models.Trap")
	proto.RegisterType((*SpeedShoes)(nil), "models.SpeedShoes")
	proto.RegisterType((*Pumpkin)(nil), "models.Pumpkin")
	proto.RegisterType((*RoomDownsyncFrame)(nil), "models.RoomDownsyncFrame")
	proto.RegisterMapType((map[int32]*Bullet)(nil), "models.RoomDownsyncFrame.BulletsEntry")
	proto.RegisterMapType((map[int32]*Player)(nil), "models.RoomDownsyncFrame.PlayersEntry")
	proto.RegisterMapType((map[int32]*Pumpkin)(nil), "models.RoomDownsyncFrame.PumpkinEntry")
	proto.RegisterMapType((map[int32]*SpeedShoes)(nil), "models.RoomDownsyncFrame.SpeedShoesEntry")
	proto.RegisterMapType((map[int32]*Trap)(nil), "models.RoomDownsyncFrame.TrapsEntry")
	proto.RegisterMapType((map[int32]*Treasure)(nil), "models.RoomDownsyncFrame.TreasuresEntry")
}

func init() { proto.RegisterFile("room_downsync_frame.proto", fileDescriptor_bfbf2753c483f827) }

var fileDescriptor_bfbf2753c483f827 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xd1, 0x6e, 0xdb, 0x36,
	0x14, 0x05, 0x2d, 0x4b, 0xb6, 0xaf, 0x0d, 0x27, 0x21, 0x86, 0x81, 0x0b, 0x86, 0x41, 0xf0, 0xb2,
	0x40, 0xc3, 0x06, 0x3f, 0x64, 0x2f, 0x43, 0x9e, 0xb6, 0x20, 0x4d, 0xe1, 0x14, 0x09, 0x52, 0x25,
	0xef, 0x01, 0x63, 0x31, 0xa8, 0x1a, 0x49, 0x14, 0x48, 0x3a, 0xb5, 0x7e, 0xa1, 0x7d, 0xe9, 0x47,
	0xf4, 0x4f, 0xfa, 0x33, 0xfd, 0x8c, 0x42, 0xa4, 0x64, 0x51, 0x89, 0xd3, 0xa0, 0xc9, 0x4b, 0xdf,
	0x74, 0x79, 0x79, 0x0f, 0xcf, 0x3d, 0x87, 0xbc, 0x10, 0xfc, 0x22, 0x38, 0x4f, 0x2f, 0x23, 0xfe,
	0x2e, 0x93, 0x45, 0x36, 0xbf, 0xbc, 0x16, 0x34, 0x65, 0xd3, 0x5c, 0x70, 0xc5, 0xb1, 0x97, 0xf2,
	0x88, 0x25, 0x72, 0xf2, 0x17, 0x0c, 0x0e, 0x63, 0xc1, 0xe6, 0x2a, 0xe6, 0x19, 0x1e, 0x43, 0x27,
	0x5a, 0x12, 0xe4, 0xa3, 0x00, 0x85, 0x9d, 0x68, 0xa9, 0xe3, 0x82, 0x74, 0xaa, 0xb8, 0x98, 0x7c,
	0xee, 0x80, 0x77, 0x96, 0xd0, 0x82, 0x89, 0x32, 0x15, 0x47, 0x7a, 0xab, 0x13, 0x76, 0xe2, 0x08,
	0x8f, 0x00, 0x2d, 0xab, 0x9d, 0x68, 0x59, 0x46, 0x05, 0x71, 0x4c, 0x54, 0xe0, 0xdf, 0xc1, 0x89,
	0x62, 0x41, 0xba, 0x3e, 0x0a, 0x86, 0x7b, 0x5b, 0x53, 0x73, 0xf2, 0x74, 0x75, 0x6c, 0x58, 0x66,
	0xf1, 0x4f, 0xe0, 0xca, 0x9c, 0xb1, 0x88, 0xb8, 0x3e, 0x0a, 0xdc, 0xd0, 0x04, 0xd8, 0x87, 0xe1,
	0x15, 0x55, 0x2a, 0x61, 0xe7, 0x8a, 0x2a, 0x46, 0x3c, 0x9d, 0xb3, 0x97, 0xf0, 0xdf, 0xb0, 0x95,
	0x50, 0xa9, 0x4e, 0xf8, 0x2d, 0x7b, 0x99, 0xaa, 0x93, 0x38, 0x49, 0x62, 0x49, 0x7a, 0x7a, 0xdf,
	0xfd, 0x04, 0xc6, 0xd0, 0xcd, 0x68, 0xca, 0x48, 0xdf, 0x47, 0xc1, 0x20, 0xd4, 0xdf, 0xe5, 0x19,
	0x51, 0x2c, 0xf3, 0x84, 0x16, 0xa7, 0x65, 0x6a, 0xa0, 0x53, 0xf6, 0x92, 0xe6, 0x36, 0xe7, 0x82,
	0x11, 0xa8, 0xb8, 0x95, 0x01, 0x26, 0xd0, 0x13, 0x2c, 0xe5, 0xb7, 0x2c, 0x22, 0x43, 0x1f, 0x05,
	0xfd, 0xb0, 0x0e, 0xf1, 0xaf, 0x30, 0x78, 0xcb, 0xe3, 0x6c, 0x96, 0x45, 0x6c, 0x49, 0x46, 0xba,
	0xa6, 0x59, 0x98, 0x7c, 0x42, 0xd0, 0xbf, 0x10, 0x8c, 0xca, 0x85, 0x60, 0x96, 0x8e, 0xae, 0xd6,
	0x31, 0x80, 0x8d, 0x84, 0xcf, 0x69, 0x32, 0x8b, 0x66, 0xd9, 0x81, 0x6e, 0x53, 0xab, 0xea, 0x86,
	0x77, 0x97, 0x1b, 0x52, 0x8e, 0x4d, 0x4a, 0xfb, 0xd0, 0x6d, 0xf9, 0xe0, 0xd6, 0x3e, 0x58, 0x84,
	0xbd, 0x36, 0x61, 0x0c, 0x5d, 0x55, 0xe4, 0xac, 0xd2, 0x4d, 0x7f, 0x4f, 0xde, 0x23, 0xf0, 0x0e,
	0x16, 0x49, 0xc2, 0xd4, 0x3a, 0x52, 0x68, 0x3d, 0x29, 0x1f, 0x86, 0x49, 0x9c, 0x31, 0x2a, 0xce,
	0xb5, 0x97, 0xe6, 0x42, 0xd8, 0x4b, 0x86, 0xa0, 0xd3, 0x22, 0xd8, 0x5d, 0x43, 0xd0, 0x6d, 0x11,
	0x2c, 0xc9, 0x74, 0x2f, 0x04, 0xcd, 0x9f, 0xa1, 0x57, 0xdd, 0xa3, 0xd3, 0xf4, 0xf8, 0x34, 0xb5,
	0x26, 0x1f, 0x11, 0x80, 0x6e, 0xe6, 0xfc, 0x0d, 0x67, 0xf2, 0x19, 0x94, 0x9e, 0xa4, 0xc5, 0xaa,
	0x11, 0xcf, 0x32, 0xeb, 0x03, 0x82, 0xde, 0xd9, 0x22, 0xcd, 0x6f, 0xe2, 0xec, 0x07, 0x70, 0xeb,
	0x4b, 0x0f, 0xb6, 0x42, 0xce, 0xd3, 0xc3, 0x6a, 0xf2, 0x1c, 0x95, 0x83, 0xe7, 0x9e, 0x4e, 0xbf,
	0x01, 0x08, 0x76, 0xad, 0x73, 0xb3, 0xa8, 0x92, 0xc8, 0x5a, 0xc1, 0xff, 0x41, 0x2f, 0xd7, 0xc3,
	0x46, 0x12, 0xc7, 0x77, 0x82, 0xe1, 0xde, 0x6e, 0x3d, 0x3a, 0xee, 0x61, 0x4f, 0xcd, 0x54, 0x92,
	0x2f, 0x32, 0x25, 0x8a, 0xb0, 0x2e, 0xc3, 0x3f, 0x83, 0x27, 0x59, 0xa6, 0xfe, 0x57, 0x9a, 0xb4,
	0x13, 0x56, 0x11, 0xde, 0x85, 0xf1, 0x9c, 0x2f, 0x32, 0x55, 0x4e, 0xc6, 0x53, 0x9a, 0x71, 0xa9,
	0x1b, 0x70, 0xc2, 0x3b, 0xab, 0xf8, 0x08, 0x06, 0xaa, 0x7a, 0xa8, 0x92, 0x78, 0x9a, 0x43, 0xf0,
	0x30, 0x87, 0xfa, 0x4d, 0x57, 0x2c, 0x9a, 0x52, 0xbc, 0x0f, 0xae, 0x12, 0x34, 0x2f, 0xe7, 0x52,
	0x89, 0xb1, 0xf3, 0x2d, 0x0c, 0x9a, 0x57, 0xf5, 0xa6, 0xa4, 0x54, 0xe1, 0x4a, 0xbf, 0x42, 0x49,
	0xfa, 0x8f, 0xa9, 0x60, 0x9e, 0x6b, 0xad, 0x42, 0x55, 0x86, 0x67, 0x00, 0x72, 0x75, 0x5b, 0xc9,
	0x40, 0x83, 0xfc, 0xf9, 0x30, 0x48, 0x73, 0xb3, 0x0d, 0x8e, 0x55, 0xac, 0x2d, 0x31, 0xb7, 0x8c,
	0xc0, 0xa3, 0x96, 0x98, 0x8d, 0xb5, 0x25, 0x26, 0xda, 0x3e, 0x86, 0x91, 0xed, 0x15, 0xde, 0x04,
	0xe7, 0x86, 0x15, 0xd5, 0xad, 0x28, 0x3f, 0xf1, 0x0e, 0xb8, 0xb7, 0x34, 0x59, 0x98, 0x47, 0x33,
	0xdc, 0x1b, 0xd7, 0x27, 0x98, 0xb2, 0xd0, 0x24, 0xf7, 0x3b, 0xff, 0xa2, 0xed, 0x53, 0x18, 0xb7,
	0x35, 0x5f, 0x83, 0xb6, 0xdb, 0x46, 0xdb, 0xac, 0xd1, 0xea, 0x42, 0x1b, 0xef, 0x08, 0xa0, 0xd1,
	0x7f, 0x0d, 0xd6, 0xa4, 0x8d, 0x35, 0x6a, 0xb0, 0x68, 0x6e, 0xe3, 0x1c, 0xc3, 0xc8, 0x76, 0xe2,
	0x3b, 0x7a, 0x34, 0x65, 0x36, 0xd6, 0x6b, 0xd8, 0xb8, 0x63, 0xc8, 0x1a, 0xb8, 0xa0, 0x0d, 0x87,
	0x6b, 0xb8, 0xa6, 0xd2, 0x86, 0x7c, 0x05, 0x23, 0xdb, 0x9b, 0x35, 0x78, 0x7f, 0xb4, 0xf1, 0x36,
	0x56, 0x16, 0x98, 0x32, 0x0b, 0xec, 0xca, 0xd3, 0xbf, 0x13, 0xff, 0x7c, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xcd, 0xb4, 0x8f, 0xc0, 0x6b, 0x08, 0x00, 0x00,
}
